---
- name: download tomcat tar file
  get_url: 
  ulr: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
  dest: /home/raju/apache-tomcat-10.0.20.tar.gz
  force_basic_auth: yes


- name: create tar file
  file:
    path: /opt/tomcat 
    state: directory

- name: extract tar file
  command: 
    cmd: sudo tar xzvf /home/raju/apache-tomcat-10.0.20.tar.gz apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICNSE